# Generated by Django 5.1 on 2024-12-27 01:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_app',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_app',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('geom_wkb', models.BinaryField()),
                ('asunto', models.CharField(choices=[('avistamiento', 'avistamiento'), ('ayuda', 'ayuda')], max_length=20)),
                ('reporte', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='fotos_reportes/')),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('geom_wkt', django.contrib.gis.db.models.fields.MultiPointField(srid=25830)),
                ('especie_gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.especies_app')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_especies_app',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.especies_app')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.reporte_app')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario_app')),
            ],
        ),
    ]
